name: Kripto Sinyal Botu

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  calistir-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Kodları indir
        uses: actions/checkout@v4

      - name: Python kurulumu
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Paketleri yükle
        run: |
          pip install -r requirements.txt

      - name: Botu çalıştır
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          echo "🔥 YENİ BOT TESTİ 🔥"
          echo "Bot dosyası kontrol ediliyor..."
          head -n 5 bot.py
          echo "Bot başlatılıyor..."
          python bot.py
